// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/programs/Cinematic.tsx": () => import("../components/mockups/programs/Cinematic.tsx"),
  "./components/mockups/programs/Editorial.tsx": () => import("../components/mockups/programs/Editorial.tsx"),
  "./components/mockups/programs/Grid.tsx": () => import("../components/mockups/programs/Grid.tsx")
};
