kind = "web"
previewPath = "/"
title = "CETI Website"
version = "1.0.0"
id = "artifacts/ceti-website"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18255

[services.development]
run = "pnpm --filter @workspace/ceti-website run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/ceti-website", "run", "build" ]
serve = "static"
publicDir = "artifacts/ceti-website/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18255"
BASE_PATH = "/"
